// Sample participant data extracted from the PARANAQUE Govt (Final) study
export const sampleParticipants = [
  {
    startedAt: new Date("2025-08-30T10:00:00Z"),
    completedAt: new Date("2025-08-30T10:07:20Z"),
    durationSeconds: 440,
    taskResults: [
      {
        taskIndex: 0,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 4.651,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 1,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 9.517,
        confidenceRating: 5,
        pathTaken: "/home/transactions-services/business-permits",
        skipped: false,
      },
      {
        taskIndex: 2,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 6.031,
        confidenceRating: 6,
        pathTaken: "/home/transactions-services/traffic-fines-violations",
        skipped: false,
      },
      {
        taskIndex: 3,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 5.509,
        confidenceRating: 7,
        pathTaken: "/home/tourism/top-establishments",
        skipped: false,
      },
      {
        taskIndex: 4,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 4.651,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 5,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 7.788,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/paranaque-yearly-budget",
        skipped: false,
      },
      {
        taskIndex: 6,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 6.633,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/health-permits-services",
        skipped: false,
      },
      {
        taskIndex: 7,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 4.401,
        confidenceRating: 7,
        pathTaken: "/home/government/city-departments",
        skipped: false,
      },
    ],
  },
  {
    startedAt: new Date("2025-08-30T11:30:00Z"),
    completedAt: new Date("2025-08-30T11:35:15Z"),
    durationSeconds: 315,
    taskResults: [
      {
        taskIndex: 0,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 5.903,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 1,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 6.976,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/business-permits",
        skipped: false,
      },
      {
        taskIndex: 2,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 8.14,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/traffic-fines-violations",
        skipped: false,
      },
      {
        taskIndex: 3,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 10.429,
        confidenceRating: 6,
        pathTaken: "/home/transparency-report/tourism/top-establishments",
        skipped: false,
      },
      {
        taskIndex: 4,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 5.903,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 5,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 8.915,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/paranaque-yearly-budget",
        skipped: false,
      },
      {
        taskIndex: 6,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 16.254,
        confidenceRating: 5,
        pathTaken: "/home/transactions-services/health-permits-services",
        skipped: false,
      },
      {
        taskIndex: 7,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 5.455,
        confidenceRating: 7,
        pathTaken: "/home/government/city-departments",
        skipped: false,
      },
    ],
  },
  {
    startedAt: new Date("2025-08-30T14:15:00Z"),
    completedAt: new Date("2025-08-30T14:20:45Z"),
    durationSeconds: 345,
    taskResults: [
      {
        taskIndex: 0,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 7.317,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 1,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 6.252,
        confidenceRating: 6,
        pathTaken: "/home/transactions-services/business-permits",
        skipped: false,
      },
      {
        taskIndex: 2,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 6.031,
        confidenceRating: 6,
        pathTaken: "/home/transactions-services/traffic-fines-violations",
        skipped: false,
      },
      {
        taskIndex: 3,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 5.599,
        confidenceRating: 6,
        pathTaken: "/home/tourism/top-establishments",
        skipped: false,
      },
      {
        taskIndex: 4,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 7.317,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 5,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 8.618,
        confidenceRating: 5,
        pathTaken: "/home/transparency-report/paranaque-yearly-budget",
        skipped: false,
      },
      {
        taskIndex: 6,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 12.5,
        confidenceRating: 4,
        pathTaken: "/home/transactions-services/health-permits-services",
        skipped: false,
      },
      {
        taskIndex: 7,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 6.087,
        confidenceRating: 5,
        pathTaken: "/home/government/city-departments",
        skipped: false,
      },
    ],
  },
  {
    startedAt: new Date("2025-08-30T16:45:00Z"),
    completedAt: new Date("2025-08-30T16:52:30Z"),
    durationSeconds: 450,
    taskResults: [
      {
        taskIndex: 0,
        successful: false,
        directPathTaken: false,
        completionTimeSeconds: 22.327,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/transactions-services/government/paranaque-profile",
        skipped: false,
      },
      {
        taskIndex: 1,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 11.986,
        confidenceRating: 7,
        pathTaken: "/home/government/transactions-services/business-permits",
        skipped: false,
      },
      {
        taskIndex: 2,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 25.926,
        confidenceRating: 7,
        pathTaken:
          "/home/transactions-services/tourism/transparency-report/transactions-services/traffic-fines-violations",
        skipped: false,
      },
      {
        taskIndex: 3,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 18.247,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/bids-and-awards-2023/tourism/top-establishments",
        skipped: false,
      },
      {
        taskIndex: 4,
        successful: false,
        directPathTaken: false,
        completionTimeSeconds: 22.327,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/transactions-services/government/paranaque-profile",
        skipped: false,
      },
      {
        taskIndex: 5,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 11.781,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/paranaque-yearly-budget",
        skipped: false,
      },
      {
        taskIndex: 6,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 16.335,
        confidenceRating: 4,
        pathTaken: "/home/government/transactions-services/health-permits-services",
        skipped: false,
      },
      {
        taskIndex: 7,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 7.213,
        confidenceRating: 4,
        pathTaken: "/home/tourism/government/city-departments",
        skipped: false,
      },
    ],
  },
  {
    startedAt: new Date("2025-08-01T09:20:00Z"),
    completedAt: new Date("2025-08-01T09:25:30Z"),
    durationSeconds: 330,
    taskResults: [
      {
        taskIndex: 0,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 8.753,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 1,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 9.383,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/business-permits",
        skipped: false,
      },
      {
        taskIndex: 2,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 15.716,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/traffic-fines-violations",
        skipped: false,
      },
      {
        taskIndex: 3,
        successful: false,
        directPathTaken: false,
        completionTimeSeconds: 31.317,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/transactions-services/business-permits",
        skipped: false,
      },
      {
        taskIndex: 4,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 8.753,
        confidenceRating: 7,
        pathTaken: "/home/government/visionmission",
        skipped: false,
      },
      {
        taskIndex: 5,
        successful: false,
        directPathTaken: true,
        completionTimeSeconds: 15.201,
        confidenceRating: 7,
        pathTaken: "/home/transparency-report/full-disclosure-report",
        skipped: false,
      },
      {
        taskIndex: 6,
        successful: true,
        directPathTaken: true,
        completionTimeSeconds: 12.168,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/health-permits-services",
        skipped: false,
      },
      {
        taskIndex: 7,
        successful: true,
        directPathTaken: false,
        completionTimeSeconds: 10.351,
        confidenceRating: 7,
        pathTaken: "/home/transactions-services/government/city-departments",
        skipped: false,
      },
    ],
  },
];
